### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jonathandhill** [SchoolOfCode/bc17-w7d3-workshop-nextjs-boilerplate-brilliant-json-krew#1]
```[tasklist]
### Tasks
- [x] Clear html and csss
- [x] Added images from old and new
- [x] copied footer and header files and imported
- [x] tested
- [x] copied over how it works and imported
- [x] Font
- [x] Sort Images
```
