### ISSUE TITLE
Menu with links

### ISSUE THREAD

**Issue by jonathandhill** [SchoolOfCode/bc17-w7d3-workshop-nextjs-boilerplate-brilliant-json-krew#3]
```[tasklist]
### Tasks
- [x] Burger menu
- [x] X close button
- [x] Logic for opening/closing
- [x] Menu covering full screen
- [x] Links for Home/Founders
```
