### ISSUE TITLE
Reviews component

### ISSUE THREAD

**Issue by jonathandhill** [SchoolOfCode/bc17-w7d3-workshop-nextjs-boilerplate-brilliant-json-krew#4]
```[tasklist]
### Tasks
- [x] Importing from React
- [x] Linked CSS
- [x] Text and links in Flex
- [x] 3 Buttons with onClicks
- [x] State for holding button value
- [x] States for holding 3 countries
- [x] useEffect rerendering when button clicked
- [x] Fetch request in useEffect updaing Review variable
- [x] Review variable rending content below buttons
- [x] Style review data as per design
```
